server {
    listen 443 ssl;
    http2 on;
    server_name portal.lobbydesbraves.test;

    ssl_certificate /etc/nginx/certs/lobby.crt;
    ssl_certificate_key /etc/nginx/keys/lobby.key;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;

    root /var/www/portal.lobbydesbraves.test;
    index index.html;
}